import Link from "next/link";
import { FeatureIcon, MiniGraph } from "@/components/visuals";
import { MotionReveal } from "@/components/motion-reveal";

const features = [
  ["ATHAR Engine", "محرك التحليل", "يفحص التعديل بقواعد قابلة للتفسير ومراجع واضحة.", "◈"],
  ["ATHAR Ripple", "الأثر المتسلسل", "يكشف كيف يصل التعديل إلى مواد وأنظمة وإجراءات مرتبطة.", "⌁"],
  ["ATHAR Radar", "كاشف التعارضات", "ينبه إلى التعارضات المحتملة، لا يصدر حكمًا قانونيًا نهائيًا.", "◎"],
  ["ATHAR Citizen", "اشرحلي حقي", "يحوّل النص التجريبي إلى شرح بسيط ومباشر للمواطن.", "◌"],
];

export default function Home() {
  return <main className="bottom-space overflow-hidden">
    <section className="relative min-h-[690px] overflow-hidden bg-[var(--navy)] py-16 text-white sm:py-24">
      <div className="grid-pattern absolute inset-0 opacity-45" /><div className="absolute -left-28 top-8 size-80 rounded-full bg-[var(--emerald)] opacity-20 blur-3xl" /><div className="absolute bottom-0 right-0 size-80 rounded-full bg-[#c69a38] opacity-10 blur-3xl" />
      <div className="shell relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
        <MotionReveal><div><div className="mb-7 flex items-center gap-3"><span className="gold-dot" /><span className="text-sm font-bold text-[#dce9ef]">ذكاء تشريعي قابل للتفسير</span></div>
          <p className="mb-3 text-lg font-bold text-[#87e0c9]">أثَر <span className="mr-2 text-xs tracking-[.22em] text-[#a8c5d1]">ATHAR AI</span></p>
          <h1 className="max-w-3xl text-[clamp(3.1rem,8vw,6.7rem)] font-black leading-[.96] tracking-[-.075em]">من النص<br /><span className="text-[#e9c76b]">إلى الأثر</span></h1>
          <p className="mt-8 max-w-xl text-lg leading-8 text-[#d7e5e9] sm:text-xl">تعديل مادة واحدة قد يمتد أثره إلى عشرات المواد والأنظمة والتعليمات.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Link href="/analyze" className="primary-btn !bg-[var(--emerald)] !px-5 !py-3">حلّل تعديلًا تشريعيًا <span aria-hidden>←</span></Link><a href="#how" className="secondary-btn !border-[#496176] !bg-transparent !text-white">استكشف كيف يعمل أثَر</a></div>
          <p className="mt-8 text-xs text-[#a8c5d1]">يعمل نموذج العرض محليًا بالكامل • لا يحتاج إلى مفتاح AI أو إنترنت</p>
        </div></MotionReveal>
        <MotionReveal delay={0.18} className="relative mx-auto w-full max-w-[510px]"><div className="absolute -inset-6 rounded-[40px] border border-[#5fd5bb]/25" /><div className="relative overflow-hidden rounded-[30px] border border-white/10 bg-[#102b43] p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs text-[#a8c5d1]">ATHAR RIPPLE</p><p className="font-bold">الأثر المتسلسل</p></div><span className="tag bg-[#f6d77e] text-[#573f05]">Demo Mode</span></div><MiniGraph /><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div><b className="block text-xl text-[#82e3cd]">6</b><span className="text-[10px] text-[#b7cbd5]">مواد مرتبطة</span></div><div><b className="block text-xl text-[#f4d779]">3</b><span className="text-[10px] text-[#b7cbd5]">تشريعات</span></div><div><b className="block text-xl text-[#ffb1a6]">مرتفع</b><span className="text-[10px] text-[#b7cbd5]">مستوى الأثر</span></div></div></div></MotionReveal>
      </div>
    </section>
    <section className="shell py-20 sm:py-28"><div className="grid gap-10 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow">المشكلة</p><h2 className="section-title mt-3">التشريع ليس وثيقة منفصلة.</h2></div><p className="max-w-xl text-lg leading-8 text-[var(--muted)]">العلاقات بين المواد والتشريعات والأنظمة والإجراءات غالبًا غير مرئية عند مراجعة تعديل واحد. والنتيجة: وقت أطول، ومخاطر يصعب شرحها، وأثر لا يظهر إلا متأخرًا.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><div className="card p-6"><b className="text-3xl text-[var(--emerald)]">01</b><p className="mt-6 font-bold">نصوص متفرقة</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">مصادر وصيغ وإحالات موزعة بين طبقات مختلفة.</p></div><div className="card p-6"><b className="text-3xl text-[var(--gold)]">02</b><p className="mt-6 font-bold">أثر مخفي</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">قد يرتبط التعديل بالحذف والإشعار والسجل دون أن يظهر فورًا.</p></div><div className="card bg-[var(--navy)] p-6 text-white"><b className="text-3xl text-[#85e2cc]">03</b><p className="mt-6 font-bold">قرار أوضح</p><p className="mt-2 text-sm leading-6 text-[#c4d5dc]">أثَر يرسم شبكة الأدلة قبل أن يفسرها.</p></div></div></section>
    <section id="how" className="bg-[#eaf2ef] py-20 sm:py-28"><div className="shell"><div className="max-w-2xl"><p className="eyebrow">كيف يعمل ATHAR</p><h2 className="section-title mt-3">نبني العلاقة أولًا، ثم نفسّر أثرها.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-4">{[["01", "اختَر نصًا", "أدخل النص الحالي والتعديل المقترح."], ["02", "حلّل القواعد", "يفحص المحرك المصطلحات والإحالات والاعتمادات."], ["03", "ارسم الأثر", "تظهر المواد المرتبطة في شبكة تفاعلية."], ["04", "راجع الدليل", "كل تنبيه يشرح سببه ومصدره التجريبي."]].map(([n, t, d]) => <div key={n} className="relative card p-6"><span className="text-sm font-black text-[var(--gold)]">{n}</span><h3 className="mt-8 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></div></section>
    <section className="shell py-20 sm:py-28"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">منظومة أثَر</p><h2 className="section-title mt-3">واجهة واحدة، مكوّنات مترابطة.</h2></div><Link className="secondary-btn" href="/analyze">جرّب النموذج ←</Link></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([english, arabic, text, glyph]) => <article className="card p-6" key={english}><FeatureIcon glyph={glyph} /><p className="mt-6 text-xs font-bold tracking-[.12em] text-[var(--emerald)]">{english}</p><h3 className="mt-1 text-lg font-black">{arabic}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div></section>
    <section className="bg-[var(--navy)] py-20 text-white"><div className="shell grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow !text-[#82e3cd]">البنية الحالية</p><h2 className="section-title mt-3">نسخة عرض صادقة، قابلة للنمو.</h2><p className="mt-5 max-w-md leading-7 text-[#c7d7de]">لا يدّعي أثَر وجود ذكاء اصطناعي خلف الكواليس. في العرض الحالي: قواعد حتمية وبيانات تجريبية ومصادر لكل علاقة.</p></div><div className="grid gap-3 sm:grid-cols-5">{["Demo Dataset", "ATHAR Engine", "Rules", "Knowledge Graph", "Cited Result"].map((item, index) => <div key={item} className="flex items-center gap-2 sm:block"><div className="rounded-xl bg-white/10 p-4 text-center text-sm font-bold">{item}</div>{index < 4 && <span className="text-[#e9c76b] sm:mx-auto sm:my-2 sm:block sm:text-center">←</span>}</div>)}</div></div></section>
    <section className="shell py-20 text-center sm:py-28"><p className="eyebrow">جاهز للعرض</p><h2 className="section-title mx-auto mt-3 max-w-2xl">حوّل التشريع من وثيقة إلى شبكة.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-[var(--muted)]">استعرض سيناريو الاحتفاظ بالبيانات الشخصية، ثم اتبع الأثر بين القانون والنظام والتعليمات والإجراءات.</p><Link href="/analyze" className="primary-btn mt-8">حلّل سيناريو العرض ←</Link></section>
  </main>;
}
