"use client";

import { useState } from "react";

const demoQuestion = "شركة طلبت مني بيانات شخصية، هل من حقي أعرف لماذا ستستخدمها؟";
export function CitizenExplainer() {
  const [question, setQuestion] = useState(""); const [showAnswer, setShowAnswer] = useState(false);
  const answer = () => { setShowAnswer(true); };
  return <section className="card overflow-hidden"><div className="bg-[var(--navy)] p-6 text-white sm:p-8"><p className="text-xs font-bold tracking-[.14em] text-[#89e5cf]">ATHAR CITIZEN</p><h1 className="mt-2 text-3xl font-black">اشرحلي حقي</h1><p className="mt-3 max-w-xl text-sm leading-7 text-[#c9dce3]">شرح مبسط مبني على بيانات التشريعات، بلغة واضحة للمواطن.</p></div><div className="p-5 sm:p-7"><label className="mb-2 block text-sm font-bold" htmlFor="citizen-question">اكتب موقفك أو سؤالك بلغة بسيطة</label><textarea id="citizen-question" className="field min-h-35 resize-y leading-7" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="مثال: شركة طلبت مني بيانات شخصية، هل من حقي أعرف لماذا ستستخدمها؟" /><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="primary-btn" onClick={answer}>اشرح لي ←</button><button type="button" className="secondary-btn" onClick={() => { setQuestion(demoQuestion); setShowAnswer(true); }}>جرّب المثال</button></div>{showAnswer && <article className="mt-6 rounded-2xl border border-[#c9e8de] bg-[#f6fffb] p-5"><span className="tag bg-[#d9f3eb] text-[#086653]">إجابة توضيحية</span><h2 className="mt-4 text-xl font-black">نعم، من حقك أن تعرف السبب بشكل واضح.</h2><p className="mt-3 leading-7 text-[var(--muted)]">وفق بيانات نموذجنا الأولي، يجب أن يكون الغرض من جمع البيانات محددًا ومعلنًا، ويجب أن يوضح إشعار الخصوصية مدة الاحتفاظ بها أو الطريقة المستخدمة لتحديدها.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-4"><b className="text-sm">لماذا؟</b><p className="mt-2 text-sm leading-6 text-[var(--muted)]">لأن الشفافية تساعدك على فهم استخدام بياناتك واتخاذ قرار واعٍ.</p></div><div className="rounded-xl bg-white p-4"><b className="text-sm">النص المرتبط</b><p className="mt-2 text-sm leading-6 text-[var(--muted)]">المادة 4: حق المعرفة — والمادة 2 من تعليمات الخصوصية الرقمية.</p></div></div><p className="mt-5 text-xs leading-6 text-[#7d641a]">هذه معلومات تشريعية مساعدة ولا تعد استشارة قانونية ملزمة. المصدر: بيانات النموذج الأولي.</p></article>}</div></section>;
}
